# The Site Configuration

# Import the theme
theme: jekyll-theme-minimal

#layout language will use the default value of 'en'
lang: en

# Change to your timezone › http://www.timezoneconverter.com/cgi-bin/findzone/findzone
timezone: America/New_York

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: Abinash # the main title

tagline: Business Central # it will display as the sub-title

description: >- # used by seo meta and the atom feed
  Here you can find my open source projects.

# fill in the protocol & hostname for your site, e.g., 'https://username.github.io'
url: "https://a-phuel.github.io"

github:
  username: a-phuel # change to your github username

# twitter:
#   username: twitter_username # change to your twitter username

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: Abinash
  email: # change to your email address
  links:
    # The first element serves as the copyright owner's link
    # - https://twitter.com/username # change to your twitter homepage
    - https://github.com/a-phuel # change to your github homepage
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

# Prefer color scheme setting.
#
# Note: Keep empty will follow the system prefer color by default,
# and there will be a toggle to switch the theme between dark and light
# on the bottom left of the sidebar.
#
# Available options:
#
#     light  - Use the light color scheme
#     dark   - Use the dark color scheme
#
theme_mode: # [light|dark]

# boolean type, the global switch for TOC in posts.
toc: true
